
CREATE TABLE CATEGORIA_1
(
	ID                   INTEGER AUTO_INCREMENT,
	CAT_NOMBRE           VARCHAR(50) NOT NULL
) AUTO_INCREMENT = 1;

ALTER TABLE CATEGORIA_1
ADD PRIMARY KEY (ID);

CREATE TABLE CATEGORIA_2
(
	ID                   INTEGER AUTO_INCREMENT,
	CAT_NOMBRE           VARCHAR(50) NOT NULL,
	CAT1_ID              INTEGER NOT NULL
) AUTO_INCREMENT = 1;

ALTER TABLE CATEGORIA_2
ADD PRIMARY KEY (ID);

CREATE TABLE CATEGORIA_3
(
	ID                   INTEGER AUTO_INCREMENT,
	CAT_NOMBRE           VARCHAR(50) NOT NULL,
	CAT2_ID              INTEGER NOT NULL
) AUTO_INCREMENT = 1;

ALTER TABLE CATEGORIA_3
ADD PRIMARY KEY (ID);

CREATE TABLE COMERCIO
(
	ID                   INTEGER AUTO_INCREMENT,
	COME_NOMBRE          VARCHAR(50) NOT NULL,
	COME_DIRECCION       VARCHAR(50) NULL,
	COME_TELEFONO        VARCHAR(20) NULL,
	COME_WEB             VARCHAR(50) NULL
) AUTO_INCREMENT = 1;

ALTER TABLE COMERCIO
ADD PRIMARY KEY (ID);

CREATE TABLE INGRESO_STOCK
(
	ID                   INTEGER AUTO_INCREMENT,
	FECHA                TIMESTAMP NOT NULL,
	CANTIDAD             INTEGER NOT NULL,
	PRE_ID               INTEGER NOT NULL
) AUTO_INCREMENT = 1;

ALTER TABLE INGRESO_STOCK
ADD PRIMARY KEY (ID);

CREATE TABLE MARCA_PRODUCTO
(
	ID                   INTEGER AUTO_INCREMENT,
	MPRO_NOMBRE          VARCHAR(50) NOT NULL
) AUTO_INCREMENT = 1;

ALTER TABLE MARCA_PRODUCTO
ADD PRIMARY KEY (ID);

CREATE TABLE PRECIO
(
	ID                   INTEGER AUTO_INCREMENT,
	PRE_VALOR            INTEGER NOT NULL,
	PROD_ID              INTEGER NOT NULL,
	PRE_FECHA            TIMESTAMP NOT NULL,
	COME_ID              INTEGER NOT NULL
) AUTO_INCREMENT = 1;

ALTER TABLE PRECIO
ADD PRIMARY KEY (ID);

CREATE TABLE PRODUCTO
(
	ID                   INTEGER AUTO_INCREMENT,
	PROD_DETALLE         VARCHAR(100) NOT NULL,
	MPRO_ID              INTEGER NOT NULL,
	CAT3_ID              INTEGER NOT NULL,
	PROD_SCAN_FORMAT     VARCHAR(20) NULL,
	PROD_SCAN_CONTENT    VARCHAR(50) NULL,
	CODIGO               VARCHAR(20) NULL
) AUTO_INCREMENT = 1;

ALTER TABLE PRODUCTO
ADD PRIMARY KEY (ID);

CREATE TABLE STOCK
(
	ID                   INTEGER AUTO_INCREMENT,
	STOC_CANTIDAD        INTEGER NOT NULL,
	FECHA                TIMESTAMP NOT NULL,
	PROD_ID              INTEGER NOT NULL
) AUTO_INCREMENT = 1;

ALTER TABLE STOCK
ADD PRIMARY KEY (ID);

ALTER TABLE CATEGORIA_2
ADD FOREIGN KEY R_4 (CAT1_ID) REFERENCES CATEGORIA_1 (ID);

ALTER TABLE CATEGORIA_3
ADD FOREIGN KEY R_5 (CAT2_ID) REFERENCES CATEGORIA_2 (ID);

ALTER TABLE INGRESO_STOCK
ADD FOREIGN KEY R_10 (PRE_ID) REFERENCES PRECIO (ID);

ALTER TABLE PRECIO
ADD FOREIGN KEY R_6 (PROD_ID) REFERENCES PRODUCTO (ID);

ALTER TABLE PRECIO
ADD FOREIGN KEY R_7 (COME_ID) REFERENCES COMERCIO (ID);

ALTER TABLE PRODUCTO
ADD FOREIGN KEY R_1 (MPRO_ID) REFERENCES MARCA_PRODUCTO (ID);

ALTER TABLE PRODUCTO
ADD FOREIGN KEY R_2 (CAT3_ID) REFERENCES CATEGORIA_3 (ID);

ALTER TABLE STOCK
ADD FOREIGN KEY R_8 (PROD_ID) REFERENCES PRODUCTO (ID);
